doc.pdf: doc.tex
	pdflatex doc.tex doc.pdf
	pdflatex doc.tex doc.pdf

presentation.pdf: presentation.tex
	pdflatex presentation.tex presentation.pdf
	pdflatex presentation.tex presentation.pdf

clean:
	rm *.log *.aux doc.pdf

